// apps/web/src/components/upstream-edit/RerankTargetEditor.vue
<script setup lang="ts">
import { computed } from 'vue';

import type { RerankProtocol, RerankTarget } from '@floway-dev/protocols/common';
import { DEFAULT_RERANK_PATHS } from '@floway-dev/protocols/rerank';
import { Input, Select } from '@floway-dev/ui';

const target = defineModel<RerankTarget>({ required: true });

defineProps<{
  disabled?: boolean;
}>();

const protocolOptions: { value: RerankProtocol; label: string }[] = [
  { value: 'cohere-v1', label: 'Cohere v1' },
  { value: 'cohere-v2', label: 'Cohere v2' },
  { value: 'jina-v1', label: 'Jina v1' },
  { value: 'voyage-v1', label: 'Voyage v1' },
  { value: 'dashscope-compatible', label: 'DashScope compatible' },
  { value: 'dashscope-native', label: 'DashScope native' },
];

const pathPlaceholder = computed(() => DEFAULT_RERANK_PATHS[target.value.protocol]);

const setProtocol = (protocol: RerankProtocol) => {
  target.value = { ...target.value, protocol };
};

const setPath = (path: string) => {
  const trimmed = path.trim();
  target.value = trimmed === ''
    ? { protocol: target.value.protocol }
    : { ...target.value, path: trimmed };
};
</script>

<template>
  <section>
    <div class="mb-3 flex items-baseline gap-3">
      <h3 class="text-[11px] font-semibold uppercase tracking-wider text-gray-500">Rerank Target</h3>
      <span class="text-[11px] text-gray-500">the request dialect and model-specific upstream path</span>
    </div>
    <div class="grid gap-3 sm:grid-cols-2">
      <label class="block space-y-1.5">
        <span class="block text-xs font-medium text-gray-500">Protocol</span>
        <Select
          :model-value="target.protocol"
          :options="protocolOptions"
          :disabled="disabled"
          @update:model-value="value => setProtocol(value as RerankProtocol)"
        />
      </label>
      <label class="block space-y-1.5">
        <span class="block text-xs font-medium text-gray-500">Path override</span>
        <Input
          :model-value="target.path"
          :readonly="disabled"
          :placeholder="pathPlaceholder"
          class="font-mono"
          @update:model-value="setPath"
        />
      </label>
    </div>
  </section>
</template>

// apps/web/src/components/upstream-editor/rerank-target-editor.tsx
import { useTranslation } from 'react-i18next';

import type { RerankProtocol, RerankTarget } from '@floway-dev/protocols/common';
import { DEFAULT_RERANK_PATHS } from '@floway-dev/protocols/rerank';

import { fluentComponents } from '../../fluent';
import { Input, Select } from '../ui/fluent-form-controls';

const { Field } = fluentComponents;

// Rerank upstreams disagree on both the request dialect and the path, and the
// pairing is per model rather than per provider, so both live on the target.
const PROTOCOL_LABELS: Record<RerankProtocol, string> = {
  'cohere-v1': 'Cohere v1',
  'cohere-v2': 'Cohere v2',
  'jina-v1': 'Jina v1',
  'voyage-v1': 'Voyage v1',
  'dashscope-compatible': 'DashScope compatible',
  'dashscope-native': 'DashScope native',
};

export const RerankTargetEditor = ({ disabled, onChange, value }: {
  disabled?: boolean;
  onChange: (target: RerankTarget) => void;
  value: RerankTarget;
}) => {
  const { t } = useTranslation();

  return <div className="grid gap-3 grid-cols-[minmax(0,1fr)_minmax(0,1fr)] max-[560px]:grid-cols-1">
    <Field className="min-w-0" label={t('dashboard.upstreamEditor.models.rerankProtocol')}>
      <Select
        disabled={disabled}
        value={value.protocol}
        onChange={(_, data) => onChange({ ...value, protocol: data.value as RerankProtocol })}
      >
        {Object.entries(PROTOCOL_LABELS).map(([protocol, label]) => (
          <option key={protocol} value={protocol}>{label}</option>
        ))}
      </Select>
    </Field>

    <Field className="min-w-0" label={t('dashboard.upstreamEditor.models.rerankPath')} hint={t('dashboard.upstreamEditor.models.rerankPathHint')}>
      <Input
        className="!w-full font-mono"
        disabled={disabled}
        placeholder={DEFAULT_RERANK_PATHS[value.protocol]}
        value={value.path ?? ''}
        onChange={(_, data) => {
          const path = data.value.trim();
          // An empty override means "use the protocol default", which is the
          // absence of the field rather than an empty string.
          onChange(path === '' ? { protocol: value.protocol } : { ...value, path });
        }}
      />
    </Field>
  </div>;
};
